# Generated by Django 2.2.5 on 2019-11-29 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('status', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('script', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('assign_to', models.ManyToManyField(to='auth.Group')),
                ('camp_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_number', models.CharField(blank=True, max_length=100, null=True)),
                ('disposition', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_disposition', models.CharField(blank=True, max_length=100, null=True)),
                ('callback_follow_up', models.CharField(max_length=100, null=True)),
                ('appointment_follow_up', models.CharField(max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='website.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('new_camp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newcamp_docs', to='website.NewCampaign')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='new_cont',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.NewCampaign'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_handler', to=settings.AUTH_USER_MODEL),
        ),
    ]
